### PR TITLE
fix: add final mark in do_clone methods to avoid warnings

### PR DESCRIPTION
**Pull request by andmax**

### CODE REVIEW

**Review by miscco — APPROVED** [review]
Thanks a lot for the contribution 🎉

**Review by allisonvacanti — APPROVED** [review]

**Comment by allisonvacanti** [comment]
Hi @andmax! Before we can merge this, we require all commits to be signed. Can you setup commit signing and remake this commit?

Info on signing is here: https://docs.github.com/articles/about-gpg/ (Using an SSH key instead of PGP is fine and generally easier to configure).

Updating the existing commit can be done with `git commit --amend -S` once the signing key is configured.

**Comment by andmax** [comment]
Hi Allison, done!  I've gpg signed the commit amending it.
Thanks,
Andre.

**Comment by allisonvacanti** [comment]
Great, thanks for the contribution!

**Pull request merged**
